### PR TITLE
File Matching

### PR DESCRIPTION
**Pull request by jescalan**
More robust file matching options!

### CODE REVIEW

**Comment by kylemac** [comment]
@jescalan since we only have 1 option, i'm not sure we need to pass an object with the `file` key. we should just let you pass a string or an array directly to the constructor. any reason you chose the `obj`?

**Comment by jescalan** [comment]
It's essentially a future-proofing and clarity thing. First, it's super clear what the argument is when you are passing it in, since you must explicitly name it. And second, if we ever decide to add any other features that can be configured, we have the ability to do so without a massive breaking change 😁

**Comment by kylemac** [comment]
ok ok, fair enough. thats a good reason, bc i can imagine us adding some more opts down the line

**Comment by jescalan** [comment]
That was mostly my reason, I can't see this staying as a single option indefinitely

**Comment by kylemac** [comment]
@jescalan add a test where we pass an array

**Pull request merged**
